---
title: "DATS6101 Group Project: App Analysis - EDA"
author: "Jonathan Giguere, Jesse Borg, Ese Emuraye, Sarah Gates"
date: "October 23rd 2019"
output:
  html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(include = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(error = FALSE)
```

```{r basicfcn, include=F}
# can add quietly=T option to the require() function
loadPkg = function(x) { if (!require(x,character.only=T, quietly =T)) { install.packages(x,dep=T,repos="http://cran.us.r-project.org"); if(!require(x,character.only=T)) stop("Package not found") } }
```

```{r, packages, include = F}
library(magrittr)
library(corrplot)
library(ggplot2)
library(plyr)
library(dplyr)
library(viridis)
library(viridisLite)
library(corrplot)
library(car)
```

```{r outlierKD_def, include=FALSE}
# modified to allow prompt-free run-through
outlierKD <- function(dt, var, rmv=NULL) { 
     var_name <- eval(substitute(var),eval(dt))
     na1 <- sum(is.na(var_name))
     m1 <- mean(var_name, na.rm = T)
     sd1 <- sd(var_name,na.rm = T)
     par(mfrow=c(2, 2), oma=c(0,0,3,0))
     boxplot(var_name, main="With outliers")
     hist(var_name, main="With outliers", xlab=NA, ylab=NA)
     outlier <- boxplot.stats(var_name)$out
     mo <- mean(outlier)
     var_name <- ifelse(var_name %in% outlier, NA, var_name)
     boxplot(var_name, main="Without outliers")
     hist(var_name, main="Without outliers", xlab=NA, ylab=NA)
     title("Outlier Check", outer=TRUE)
     na2 <- sum(is.na(var_name))
     cat("Outliers identified:", na2 - na1, "n")
     cat("Propotion (%) of outliers:", round((na2 - na1) / sum(!is.na(var_name))*100, 1), "n")
     cat("Mean of the outliers:", round(mo, 2), "n")
     m2 <- mean(var_name, na.rm = T)
     cat("Mean without removing outliers:", round(m1, 2), "n")
     cat("Mean if we remove outliers:", round(m2, 2), "n")
     #
     if(is.null(rmv)) { 
       response <- readline(prompt="Do you want to remove outliers and to replace with NA? [yes/no]: ") 
     } else {
       if (rmv=='y'|rmv=='yes'|rmv=='Y'|rmv=='Yes'|rmv=='YES'|rmv==TRUE ) { response = 'y' } else { response = 'n' }
     }
     #
     if(response == "y" | response == "yes"){
          dt[as.character(substitute(var))] <- invisible(var_name)
          assign(as.character(as.list(match.call())$dt), dt, envir = .GlobalEnv)
          cat("Outliers successfully removed", "n")
          return(invisible(dt))
     } else{
          cat("Nothing changed", "n")
          return(invisible(var_name))
     }
}
```

Google Play Dataset Structure

```{r import Google Play Data, echo=F}
library("stringr")
googlePlay <- read.csv('googleplaystore.csv')
googlePlay <- subset(googlePlay, select = -c(Android.Ver, Genres) )
googlePlay$Size <- str_remove(googlePlay$Size, 'M')
str(googlePlay)
```

Apple Store Dataset Structure

```{r import Apple Store Data, echo=F}
appleStore <- read.csv('applestore.csv')
appleStore <- subset(appleStore, select = -c(id, currency, rating_count_ver,
                                             user_rating_ver, sup_devices.num,
                                             ipadSc_urls.num, lang.num,
                                             vpp_lic))
colnames(appleStore) <- c('X', 'App', 'Size', 'Price', 'Reviews',
                          'Rating', 'Current_Ver', 'Content_Rating',
                          'Category')
appleStore$Size <- round(appleStore$Size/1000000, 0)
str(appleStore)
```


Graph of NA Values

```{r check NA, echo = F, include = T}

# review how many fields are NA
barplot(colSums(is.na(googlePlay)),
  col = "lightblue",
  main = "Playstore NA Values",
  ylab = "Count of Null Values",
  xlab = "",
  las = 2,
  cex.names = 0.7)

title(xlab="App Category", line=4, cex.lab=1.2)
```

```{r clean NA, echo = F, include = F}

# create new data frame for apps where NA is null, then remove rating NAs from main playstore dataset
ratingNA <- subset(googlePlay, is.na(Rating))
googlePlay = na.omit(googlePlay)

# to double check that the NAs have been removed
sapply(googlePlay,function(x)sum(is.na(x)))
```


```{r identify dups, echo = F, include = F}

# count of unique app names exist in the Google Play Store dataset
distinct <- nrow(googlePlay %>%
  distinct(App))

duplicates <- nrow(googlePlay) - distinct
```

```{r remove dups, echo = F, include = F}

# remove rows with duplicate app names
googlePlay = googlePlay[!duplicated(googlePlay$App), ]


# double check that the duplicates have been removed
distinct <- nrow(googlePlay %>%
  distinct(App))

nrow(googlePlay) - distinct
```

```{r order installs, echo = F, include = F}

googlePlay$Installs <- factor(googlePlay$Installs, order = TRUE, 
       levels = c("0", "0+", "1+", "5+", "10+", "50+", "100+", "500+", "1,000+", "5,000+", "10,000+", "50,000+", "100,000+", "500,000+", "1,000,000+", "5,000,000+", "10,000,000+", "50,000,000", "100,000,000+", "500,000,000+", "1,000,000,000+"))

```

```{r test, echo = F, include = F}

# create InstallsNum, which creates a new column from Installs and changes it to a numeric type
googlePlay <- googlePlay %>%
  mutate(
    InstallsNum = gsub("\\+", "", as.character(Installs)),
    InstallsNum = as.numeric(gsub(",", "", InstallsNum)),
    Rating = as.numeric(Rating),
    Reviews = as.numeric(Reviews)
  )%>%
  filter(
    Type %in% c("Free", "Paid")
  )

extract = c("Rating","Reviews","InstallsNum")
googlePlay.extract = googlePlay[extract]
googlePlay.extract %>% 
  filter(is.nan(googlePlay.extract$Reviews)) %>% 
  filter(is.na(googlePlay.extract$InstallsNum)) %>%
  filter(is.na(googlePlay.extract$Rating))
```

```{r log scale aggregate, echo = F, include = F}

# creates InstallsLog

googlePlay <- googlePlay %>%
  mutate(InstallsLog = Installs)

googlePlay$InstallsLog <- gsub("5","1", googlePlay$InstallsLog)

googlePlay$InstallsLog <- factor(googlePlay$InstallsLog, order = TRUE, 
       levels = c("0", "0+", "1+", "10+", "100+", "1,000+", "10,000+", "100,000+", "1,000,000+", "10,000,000+", "100,000,000+", "1,000,000,000+"))
```

``` {r type, echo = F}
# Create two new dataframes for free and paid apps separately
freeApps <- subset(googlePlay, googlePlay$Price == 0.00)
paidApps <- subset(googlePlay, googlePlay$Price != 0.00)

```

```{r echo=F}
# clean price column and split into categories
# strip the dollar sign off the price and convert to numeric data type
  paidApps$Price <- as.numeric(str_remove(paidApps$Price, '\\$'))

# Create new column and a split price into different categories
  paidApps$PriceCategory <- cut(paidApps$Price, breaks = c(0, 10, 100, 401), labels = c("Cheap", "Expensive", "Very Expensive"), right=FALSE)
```


```{r rating distributions for each}
hist(googlePlay$Rating, main = 'Frequency of Ratings for the Google Play Store', xlab = 'Rating', col = viridis(20),
     xlim=c(0,5))
hist(appleStore$Rating, main = 'Frequency of Ratings for the App Store', xlab = 'Rating', col = viridis(12),
     xlim=c(0, 5))
```



```{r Rating Mean and SD, echo=F, include=F}
#Get average ratings for both stores
avg_rating_google <- round(mean(googlePlay$Rating), 2)
avg_rating_apple <- round(mean(appleStore$Rating), 2)

#Get standard deviations of ratings for both stores
sd_rating_google <- round(sd(googlePlay$Rating), 2)
sd_rating_apple <- round(sd(appleStore$Rating), 2)

avg_rating_google
avg_rating_apple

sd_rating_google
sd_rating_apple
```

```{r # of reviews exploration, echo=F, include=F}
#find common apps in both datasets
a <-intersect(googlePlay$App, appleStore$App)

#subset new dataframes that contain the common apps in each store
googleCommon <- googlePlay[googlePlay$App %in% a, ]

#Remove duplicate app records
googleCommon <- distinct(googleCommon, App, .keep_all = T)

appleCommon <- appleStore[appleStore$App %in% a, ]

#Number of apps in common
length(appleCommon$X)
length(googleCommon$App)
```

```{r ratings histogram-common apps}
#hist(googleCommon$Rating, main = 'Histogram of frequency rating for the Google Playstore', xlab = 'Rating', col = viridis(20),
     #xlim=c(0,5))
#hist(appleCommon$Rating, main = 'Histogram of frequency rating for the Apple Store', xlab = 'Rating', col = viridis(12),
     #xlim=c(0,5))
```

```{r Rating Mean and SD for common, echo=F, include=F}
#Get average ratings for both stores
avg_rating_common_google <- round(mean(googleCommon$Rating), 2)
avg_rating_common_apple <- round(mean(appleCommon$Rating), 2)

#Get standard deviations of ratings for both stores
sd_rating_common_google <- round(sd(googleCommon$Rating), 2)
sd_rating_common_apple <- round(sd(appleCommon$Rating), 2)

avg_rating_common_google
avg_rating_common_apple

```

```{r get new dataframe to make price boxplots}
googleCommonBoxplot <- googleCommon
#Add column of 1s to identify google store
googleCommonBoxplot$StoreType <- as.factor(rep(1, nrow(googleCommonBoxplot)))
#Select only columns needed for barchart
googleCommonBoxplot <- select(googleCommonBoxplot, c(App, Price, StoreType))
#Change price from factor to character bc cannot go straight to num
googleCommonBoxplot$Price <- as.character(googleCommonBoxplot$Price)
#Now drop dollar sign and convert to numeric
googleCommonBoxplot$Price <- as.numeric(gsub("\\$", "", googleCommonBoxplot$Price))


appleCommonBoxplot <- appleCommon
#Add column of 0s to identify apple store
appleCommonBoxplot$StoreType <- as.factor(rep(0, nrow(appleCommonBoxplot)))
#Select only columns needed for barchart
appleCommonBoxplot <- select(appleCommonBoxplot, c(App, Price, StoreType))

#Put the dataframes together
price_compare_DF <- rbind(googleCommonBoxplot, appleCommonBoxplot)
```

```{r Make barchart}

ggplot(price_compare_DF, aes(x=StoreType, y=Price, fill = StoreType)) +
  geom_col() +
  coord_flip() +
  labs(y='Price $ USD') +
  ggtitle("Total Cost of Apps for Apps Found in Both Stores") +
  theme(legend.position = 'none', plot.title = element_text(hjust = 0.5), axis.title.y = element_blank()) +
  scale_x_discrete(labels=c("0" = "App Store", "1" = "Google Play Store")) +
  scale_fill_manual("legend", values=c("0"="aquamarine4", "1"="aquamarine3"))
```

```{r pie}
#appleStore$Type <- factor(ifelse(appleStore$Price == 0.00, 0, 1), labels = c('Free', 'Paid'))

#ggplot(appleStore, aes(x = " ", y=Type, fill = Type)) +
  #geom_bar(stat = "identity") +
  #ggtitle('Price Composition of Apps in the Appstore') +
  #coord_polar("y", start=0) +
  #theme_void()

#ggplot(googlePlay, aes(x = " ", y=Type, fill = Type)) +
  #geom_bar(stat = "identity") +
  #ggtitle('Price Composition of Apps in the Google Playstore') +
  #coord_polar("y", start=0) +
  #theme_void()
```

```{r bar2, echo = F}
ggplot(googlePlay, aes(Category)) + 
        geom_bar(fill = viridis(33), color = 'black') +
        ggtitle('Number of Apps in the Google Playstore by Category') +
        ylab('Number of Apps') +
        coord_cartesian(ylim = c(0,1250)) +
        theme_classic() +
        theme(plot.title = element_text(hjust = 0.5)) + 
        theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 8, color = 'black'))
```


```{r bary, echo = F}
catrating <- aggregate(googlePlay$Rating, list(googlePlay$Category), mean, na.rm = TRUE)
names(catrating) <- c('Category', 'Avg_Rating')

ggplot(catrating, aes(x = reorder(Category, -Avg_Rating), y = Avg_Rating)) +
        geom_bar(stat = 'Identity', fill = viridis(33), color = 'black') +
        ggtitle('Average Rating of Apps in the Google Playstore by Category') +
        ylab('Average Rating') +
        coord_cartesian(ylim = c(3.75, 4.5)) +
        theme_classic() +
        theme(plot.title = element_text(hjust = 0.5)) +
        theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 8, color = 'black'))
```

``` {r type2, include = F}
free <- subset(googlePlay, googlePlay$Type == 'Free')
paid <- subset(googlePlay, googlePlay$Type == 'Paid')

print(nrow(free))
print(nrow(paid))
```

```{r barx, echo = F}
paid$Cost = as.numeric(gsub("\\$", "", paid$Price))
catprice <- aggregate(paid$Cost, list(paid$Category), mean)
names(catprice) <- c('Category', 'Avg_Price')

ggplot(catprice, aes(x = Category, y = Avg_Price)) +
        geom_bar(stat = 'Identity', fill = viridis(28), color = 'black') + 
        ggtitle('Average Price of Paid Apps in the Google Playstore by Category') +
        ylab('Average Price ($)') +
        coord_cartesian(ylim = c(0,20)) +
        theme_bw() +
        theme(plot.title = element_text(hjust = 0.5)) + 
        theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 7, color = 'black')) +
        theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```


```{r percentile, include = F}
quantile(googlePlay$Rating, .95)
```

```{r best rated}
top_rated <- subset(googlePlay, googlePlay$Rating >= 4.8)
top_count <- plyr::count(top_rated$Category)
names(top_count) <- c('Category', 'Count')
top_count <- top_count[order(top_count$Count, decreasing = TRUE),]
```

```{r topplot}
ggplot(top_count, aes(x = reorder(Category, -Count), y = Count)) +
        geom_bar(stat = 'Identity', fill = plasma(32), color = 'black') + 
        ggtitle('Highly Rated Apps in the Google Play Store by Category') +
        ylab('Total') +
        xlab('Category') +
        coord_cartesian(ylim = c(0,60)) +
        theme_bw() +
        theme(plot.title = element_text(hjust = 0.5)) + 
        theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 7, color = 'black')) +
        theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```

Categories with the most highly rated apps.

```{r topr}
head(top_count[order(top_count$Count, decreasing = TRUE),], n = 5)
```

```{r echo=F}
# Create new dataframe and new column, assign categorical values of 0 and 1 for free and paid apps respectively   
  googlePlay_cat <- googlePlay[which(googlePlay$Price == 0.00 |googlePlay$Price != 0.00), ]
  googlePlay_cat$PriceCat <- factor(ifelse(googlePlay_cat$Price == 0.00, 0, 1), labels = c("Free", "Paid"))
  
  ggplot(googlePlay_cat, aes(x = Category, y = Rating)) +
    geom_boxplot(fill=viridis(61)) +
    #ggtitle("Boxplot of User Rating by Genre across Free Vs Paid Apps")
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5)) +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 6, color = 'black')) +
    facet_grid(. ~ PriceCat)
```

```{r echo = F}
# create new dataframe containing different categories and their respective average rating for free apps
catFreeRating = freeApps %>% group_by(Category) %>% dplyr::summarise( Avg_rating = mean(Rating)) %>% arrange(desc(Avg_rating)) %>% mutate(Category = factor(Category, levels = unique(Category)))

ggplot(catFreeRating, aes(x = Category, y = Avg_rating)) + 
  geom_bar(stat = 'Identity', fill = viridis(33), color = "black") +
  ggtitle("Average Rating of Free Apps by Category") +
  ylab('Average Rating') +
  coord_cartesian(ylim = c(3, 5)) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 9, color = 'black')) +
  theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```


```{r echo = F}
# create new dataframe containing different categories and their respective average rating for paid apps

catPaidRating = paidApps %>% group_by(Category) %>% dplyr::summarise( Avg_rating = mean(Rating)) %>% arrange(desc(Avg_rating)) %>% mutate(Category = factor(Category, levels = unique(Category)))

ggplot(catPaidRating, aes(x = Category, y = Avg_rating)) + 
  geom_bar(stat = 'Identity', fill = viridis(28), color = "black") +
  ggtitle("Average Rating of Paid Apps by Category") +
  ylab('Average Rating') +
  coord_cartesian(ylim = c(3, 5)) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 9, color = 'black')) +
  theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank())

```


```{r echo=F}
  ggplot(googlePlay_cat, aes(x = Content.Rating, y = Rating)) +
      geom_boxplot(fill=viridis(10)) +
      ggtitle("Boxplot of User Rating by Content Rating across Free Vs Paid Apps")+
      facet_grid(. ~ PriceCat) +
      theme_bw() +
      theme(plot.title = element_text(hjust = 0.5)) +
      theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
      theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 6, color = 'black'))      
```


```{r d, echo = F}
# create a dataframe sorted by count of category for free apps and plot
freeAppsCount <- freeApps %>% group_by(Category) %>% dplyr::summarise(NumOfApps = n()) %>% arrange(NumOfApps) %>% mutate(Category = factor(Category, levels = unique(Category)))


 ggplot(freeAppsCount, aes(x=Category, y=NumOfApps)) +
  geom_bar( fill = viridis(33), color = 'black', stat = 'identity') +
  ggtitle('Free Apps in the Google Playstore by Category') + 
  xlab('Category') + ylab('Number of Apps') + 
  #coord_cartesian(ylim = c(0, 1800)) + 
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 8, color = 'black')) +
  theme(axis.text.y = element_text(size = 8, color = 'black')) +
  coord_flip()

```


```{r echo = F}
# create a dataframe sorted by count of category for paid apps and plot
paidAppsCount <- paidApps %>% group_by(Category) %>% dplyr::summarise(NumOfApps = n()) %>% arrange(NumOfApps) %>% mutate(Category = factor(Category, levels = unique(Category)))

ggplot(paidAppsCount, aes(x = Category, y = NumOfApps)) +
  geom_bar(fill = viridis(28), color = 'black', stat = 'identity') +
  ggtitle('Paid Apps in Google Playstore by Category') + 
  xlab('Category') + ylab('Number of Apps') + 
  #coord_cartesian(ylim = c(0, 200)) + 
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 8, color = 'black')) +
  theme(axis.text.y = element_text(size = 8, color = 'black')) +
  coord_flip()
```


```{r echo=F}
# Plot bar chart showing the number of apps for different price categories
  ggplot(paidApps, aes(PriceCategory)) +
  geom_bar(fill = viridis(3), color = 'black') +
  ggtitle('Paid Apps in Google Playstore by Price Category') + 
  xlab('Price Category') + ylab('Number of Apps') + 
  coord_cartesian(ylim = c(0, 700)) + 
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 1, size = 8, color = 'black'))
```
 
```{r echo=F}
# create a data frame, group by price category, calulate and sort by average rating
priceCatRating = paidApps %>% group_by(PriceCategory) %>% summarise( Avg_rating = mean(Rating)) %>% arrange(Avg_rating)

# Plot bar chart showing the average rating for different price categories
ggplot(priceCatRating, aes(x = PriceCategory, y = Avg_rating)) + 
  geom_bar(stat = 'Identity', fill = viridis(3), color = "black") +
  ggtitle("Average Rating of Paid Apps by Price Category") +
   ylab('Average Rating') +
   xlab('Price Category') +
  coord_cartesian(ylim = c(2.5, 5.5)) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(axis.text.x = element_text(angle = 0, hjust = 1, size = 9, color = 'black')) +
  theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```


```{r echo=F}
# Create dataframe and store Price Category and User Rating columns and perform anova
    priceCatRating <- subset(paidApps, select = c("PriceCategory", "Rating"))
    anovaRatingPrice <- aov(Rating ~ PriceCategory,  data=priceCatRating)
    summary(anovaRatingPrice)
    anovaRatPrice <- summary(anovaRatingPrice)
    anovaRatPrice[[1]][[5]][[1]]
```

```{r echo=F}
  # perform a tukeyHSD test
  tukeyRatingPrice <- TukeyHSD(anovaRatingPrice)
  tukeyRatingPrice
```

```{r echo = F}
# Create a boxplot of user rating by different price categories
ggplot(priceCatRating, aes(x = PriceCategory, y = Rating)) +
      geom_boxplot(fill=viridis(3)) +
      ggtitle("Boxplot of User Rating by Price Category")+
      ylab("User Rating") +
      xlab("Price Category") +
      theme_bw() +
      theme(plot.title = element_text(hjust = 0.5)) +
      theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
      theme(axis.text.x = element_text(angle = 0, hjust = 0.5, size = 10, color = 'black'))
```

```{r echo=F}
# clean installs column and cast to numeric
  paidApps$Installs <- str_remove(paidApps$Installs, '\\+')
  paidApps$Installs <- as.numeric(gsub(',','',paidApps$Installs))

# create dataframe and store numerical variables
  lcpaidApps <- subset(paidApps, select = c("Rating", "InstallsNum", "Price"))

# Get correlation matrix for all numerical variables
  paidAppsCor = cor(lcpaidApps)
  corrplot(paidAppsCor, method = 'number')

```

```{r include=F}
# fit the price to the rating
  lm1 = lm(Rating ~ Price, data = lcpaidApps)
  summary(lm1)
```

```{r include=F}
# fit the number of app installs to the rating
  lm2 = lm(Rating ~ InstallsNum, data = lcpaidApps)
  summary(lm2)
```

```{r include=F}
# fit the price and number of app installs to the rating
  lm3 = lm(Rating ~ Price+InstallsNum, data = lcpaidApps)
  summary(lm3)
  vif(lm3)
```

```{r corrplot, echo = F, include = T}

# Correlation plot between rating, reviews, and installs

googlePlay.extract = na.omit(googlePlay.extract)
cor_matrix = cor(googlePlay.extract)
corrplot(cor_matrix,method = "color",order = "AOE",addCoef.col = "grey")
```

```{r Rating Histogram, echo = F, include = T}

# Ratings histogram

ratingHist <- ggplot(googlePlay, aes(x = Rating)) + 
 geom_histogram(aes(y=..density..), colour="black", fill="white", binwidth = .2)+
 geom_density(alpha=.2, fill="#FF6666") 

ratingHist
```

```{r Installs Histogram, echo = F, include = T}

googlePlay %>% 
  group_by(InstallsLog) %>% 
  summarise(count = n()) %>%
  suppressWarnings()


installsHist <- ggplot(subset(googlePlay, !is.na(InstallsLog)), aes(x = InstallsLog)) + 
 geom_bar(aes(y= ..count..), colour="black", fill="#AFEEEE", na.rm = TRUE)+
 geom_density(alpha=.2, fill="#AFEEEE") +
 theme(axis.text.x = element_text(angle = 50, hjust = 1))

suppressWarnings(installsHist)
```

```{r Rating Histogram2, include = T}

reviewsHist <- ggplot(googlePlay, aes(x = Reviews)) + 
 geom_histogram(aes(y=..density..), colour="black", fill="#b19cd9") +
 stat_bin(bins = 30) +
 ylab('Density')

suppressWarnings(reviewsHist)
```
